import jsPDF from "jspdf";
import { DeepfakeReportDto } from "../types/deepFakeReport";

export function generatePdfReport(result: DeepfakeReportDto) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const margin = 48;
  const footerSafeY = H - 70; // leave room for footer band
  let y = 0;

  const analysis = result.analysis;
  const isAudio = result.fileType?.startsWith("audio/");

  const isFake =
    result.verdict.toLowerCase().includes("fake") ||
    result.verdict.toLowerCase().includes("manipulated") ||
    result.verdict.toLowerCase().includes("generated") ||
    result.verdict.toLowerCase().includes("voice");

  // Same fallback logic as ResultView: prefer analysis score, fall back to confidenceScore
  const displayScore = analysis?.overallForgeryScore ?? result.confidenceScore;

  const verdictColor: [number, number, number] = isFake
    ? [220, 50, 50]
    : [60, 160, 80];
  const verdictBg: [number, number, number] = isFake
    ? [255, 240, 240]
    : [240, 255, 244];

  // ---- helpers ----

  function drawHeader() {
    doc.setFillColor(10, 10, 10);
    doc.rect(0, 0, W, 80, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(255, 255, 255);
    doc.text("IDAi", margin, 32);

    doc.setFontSize(10);
    doc.setTextColor(180, 180, 180);
    doc.text("Deepfake Detection Report", margin, 50);

    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    const generated = `Generated: ${new Date().toUTCString()}`;
    doc.text(generated, W - margin, 50, { align: "right" });
  }

  function drawFooter(pageNum: number) {
    doc.setFillColor(10, 10, 10);
    doc.rect(0, H - 60, W, 60, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text("IDAi", margin, H - 35);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(130, 130, 130);
    doc.text(
      "This report is generated by automated AI analysis. Results should be verified by qualified professionals.",
      margin,
      H - 20
    );

    doc.setTextColor(90, 90, 90);
    doc.text(`Page ${pageNum}`, W - margin, H - 20, { align: "right" });
  }

  // Adds a new page (with header) if the next block won't fit before the footer zone
  function checkPageBreak(neededHeight: number) {
    if (y + neededHeight > footerSafeY) {
      doc.addPage();
      drawHeader();
      y = 110;
    }
  }

  function sectionTitle(title: string) {
    checkPageBreak(40);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(50, 50, 50);
    doc.text(title, margin, y);
    y += 6;
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, y, W - margin, y);
    y += 16;
  }

  // Wraps text to the page width and returns the new y
  function wrappedText(text: string, fontSize: number, color: [number, number, number], lineGap = 14) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(fontSize);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, W - margin * 2);
    for (const line of lines) {
      checkPageBreak(lineGap);
      doc.text(line, margin, y);
      y += lineGap;
    }
  }

  // A single labeled horizontal score bar (used for authenticity/fake-prob and category scores)
  function scoreBar(label: string, score: number, color: [number, number, number], barH = 10) {
    checkPageBreak(34);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(label, margin, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...color);
    doc.text(`${score}%`, W - margin, y, { align: "right" });
    y += 8;

    const barW = W - margin * 2;
    doc.setFillColor(230, 230, 230);
    doc.roundedRect(margin, y, barW, barH, barH / 2, barH / 2, "F");
    doc.setFillColor(...color);
    doc.roundedRect(margin, y, (score / 100) * barW, barH, barH / 2, barH / 2, "F");
    y += barH + 18;
  }

  // ---- start rendering ----

  drawHeader();
  y = 110;

  // FILE INFORMATION
  sectionTitle("FILE INFORMATION");

  const fileRows: [string, string][] = [
    ["Filename", result.originalFilename],
    ["File Type", result.fileType],
    ["File Size", result.fileSize],
    ["Scan Time", new Date(result.scanTimestamp).toUTCString()],
  ];
  if (analysis?.imageType) {
    fileRows.splice(2, 0, ["Image Type", analysis.imageType]);
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  for (const [label, value] of fileRows) {
    checkPageBreak(18);
    doc.setTextColor(120, 120, 120);
    doc.text(label, margin, y);
    doc.setTextColor(30, 30, 30);
    doc.text(value, margin + 120, y);
    y += 18;
  }
  y += 10;

  // VERDICT
  checkPageBreak(72);
  doc.setFillColor(...verdictBg);
  doc.roundedRect(margin, y, W - margin * 2, 52, 6, 6, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...verdictColor);
  doc.text("VERDICT", margin + 16, y + 18);

  doc.setFontSize(16);
  doc.text(result.verdict, margin + 16, y + 38);

  if (analysis?.riskLevel) {
    doc.setFontSize(10);
    doc.text(`${analysis.riskLevel} Risk`, W - margin - 16, y + 30, { align: "right" });
  }
  y += 72;

  // OVERALL SCORE
  sectionTitle(isAudio ? "AI VOICE PROBABILITY" : "OVERALL FORGERY SCORE");

  checkPageBreak(60);
  const barW = W - margin * 2;
  const fillW = (displayScore / 100) * barW;

  doc.setFillColor(230, 230, 230);
  doc.roundedRect(margin, y, barW, 12, 4, 4, "F");
  doc.setFillColor(...verdictColor);
  doc.roundedRect(margin, y, fillW, 12, 4, 4, "F");

  y += 22;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...verdictColor);
  doc.text(`${displayScore}%`, margin, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(140, 140, 140);
  doc.text("Authentic", margin, y + 14);
  doc.text("Fake / AI-generated", W - margin, y + 14, { align: "right" });
  y += 40;

  // ANALYSIS SUMMARY
  if (analysis?.analysisSummary) {
    sectionTitle("ANALYSIS SUMMARY");
    wrappedText(analysis.analysisSummary, 10, [40, 40, 40], 14);
    y += 8;

    if (analysis.recommendation) {
      checkPageBreak(20);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9.5);
      doc.setTextColor(110, 110, 110);
      const recLines = doc.splitTextToSize(`Recommendation: ${analysis.recommendation}`, W - margin * 2);
      for (const line of recLines) {
        checkPageBreak(14);
        doc.text(line, margin, y);
        y += 14;
      }
    }
    y += 10;
  }

  // AUDIO-SPECIFIC: Authenticity Breakdown bars + snapshots
  if (isAudio) {
    if (analysis) {
      sectionTitle("AUTHENTICITY BREAKDOWN");
      const authScore = analysis.authenticityScore ?? 100 - displayScore;
      const fakeScore = analysis.fakeProbabilityScore ?? displayScore;
      scoreBar("Authenticity", authScore, [60, 160, 80]);
      scoreBar("Fake Probability", fakeScore, [220, 50, 50]);
    }

    if (analysis?.audioSnapshots?.length) {
      sectionTitle("STRONGEST EVIDENCE SNAPSHOTS");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      for (const snap of analysis.audioSnapshots) {
        checkPageBreak(36);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(40, 40, 40);
        doc.text(`${snap.timestampLabel} — ${snap.signalLabel}`, margin, y);
        y += 14;
        const descLines = doc.splitTextToSize(snap.description, W - margin * 2);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(110, 110, 110);
        for (const line of descLines) {
          checkPageBreak(13);
          doc.text(line, margin, y);
          y += 13;
        }
        y += 8;
      }
      y += 4;
    }
  } else {
    // IMAGE / VIDEO: Detailed breakdown category scores
    if (analysis?.detailedBreakdown?.length) {
      sectionTitle("DETAILED BREAKDOWN");
      for (const cat of analysis.detailedBreakdown) {
        const catColor: [number, number, number] =
          cat.score < 20 ? [60, 160, 80] : cat.score < 50 ? [217, 119, 6] : [220, 50, 50];
        scoreBar(cat.category, cat.score, catColor, 8);
        if (cat.explanation) {
          doc.setFont("helvetica", "normal");
          doc.setFontSize(9);
          doc.setTextColor(130, 130, 130);
          const lines = doc.splitTextToSize(cat.explanation, W - margin * 2);
          for (const line of lines) {
            checkPageBreak(12);
            doc.text(line, margin, y);
            y += 12;
          }
          y += 10;
        }
      }
    }

    if (analysis?.strongestEvidenceSnapshots?.length) {
      sectionTitle("STRONGEST EVIDENCE SNAPSHOTS");
      for (const e of analysis.strongestEvidenceSnapshots) {
        checkPageBreak(30);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9.5);
        doc.setTextColor(180, 100, 20);
        doc.text(e.label, margin, y);
        y += 13;
        doc.setFont("helvetica", "normal");
        doc.setTextColor(110, 110, 110);
        const lines = doc.splitTextToSize(e.description, W - margin * 2);
        for (const line of lines) {
          checkPageBreak(12);
          doc.text(line, margin, y);
          y += 12;
        }
        y += 8;
      }
      y += 4;
    }
  }

  // FALLBACK: legacy raw signals (only if no structured analysis was returned at all)
  if (!analysis && result.signals && result.signals.length > 0) {
    sectionTitle("SIGNAL BREAKDOWN");

    checkPageBreak(20);
    doc.setFillColor(245, 245, 245);
    doc.rect(margin, y - 4, W - margin * 2, 20, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(90, 90, 90);
    doc.text("Signal", margin + 8, y + 9);
    doc.text("Score", W - margin - 110, y + 9);
    doc.text("Confidence", W - margin - 8, y + 9, { align: "right" });
    y += 22;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    for (const s of result.signals) {
      checkPageBreak(20);
      doc.setTextColor(40, 40, 40);
      doc.text(s.name, margin + 8, y);
      doc.text(`${(s.score * 100).toFixed(1)}%`, W - margin - 110, y);
      doc.text(`${s.confidence}%`, W - margin - 8, y, { align: "right" });

      doc.setDrawColor(235, 235, 235);
      doc.line(margin, y + 5, W - margin, y + 5);
      y += 20;
    }
    y += 10;
  }

  // DETECTION METHOD
  sectionTitle("DETECTION METHOD");

  checkPageBreak(36);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text("Method", margin, y);
  doc.setTextColor(30, 30, 30);
  doc.text(result.detectionMethod ?? "AI-based multimodal analysis", margin + 120, y);
  y += 18;

  doc.setTextColor(120, 120, 120);
  doc.text("Model Version", margin, y);
  doc.setTextColor(30, 30, 30);
  doc.text(result.modelVersion ?? "N/A", margin + 120, y);

  // FOOTERS — draw on every page now that content can span multiple pages
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawFooter(p);
  }

  // SAVE
  const safeName = result.originalFilename.replace(/\.[^.]+$/, "");
  doc.save(`IDAi_Report_${safeName}.pdf`);
}